console.log("hello world")
console.log("Good Morning World!")
console.log("Hello Senku!")
console.log("i will make myself proud one day !")
console.log("Make it!")
console.log("I am so tired, but i have goals!")
console.log("gg")